### ISSUE TITLE
Selector resolve timeout too short

### ISSUE THREAD

**Issue by layflags** [HenrikJoreteg/create-selector#3]
Hi Henrik,

I currently use `redux-bundler` for a SPA at a big Telco company. The App currently has >920 selectors and lots of bundles. The crazy thing is, that in Chrome on Windows and Linux (Ubuntu) I reach the selector resolve timeout limit. Chrome on MacOS works fine, as well as FF on all systems.

To solve this problem I just shitfixed `node_modules/redux-bundler/dist/redux-bundler.m.js` by replacing `>500` with `>1000` on `postinstall`.

Have you ever experienced this issue in a bigger SPA? Do you have a recommendation on how to avoid reaching the timeout limit? Or would it be ok to just increase the timeout to 1000 msec in the `create-selector` package and publish a new version of `redux-bundler`?

Thanks!

https://github.com/HenrikJoreteg/create-selector/blob/9bca83748ba85a66c15a69d1f3cae43b08038088/src/index.js#L98

**Comment by HenrikJoreteg** [comment]
That's an interesting issue. I did wonder, when i first set this limit, what was reasonable. The reason for setting one at all, was kind of as a safety check, I figured if this limit were ever hit it would be indicative of a problem. But, if the main thread is busy doing lots of other things and with you having that many selectors, I could see it potentially happening.

I'm not opposed to increasing the limit, but I do wonder if there isn't something else that's causing it to take longer. That's an awfully long time for it to be stuck in a loop.

I have an app with a little over 300 selectors (nearly all string references that need to be resolved) and I just checked, it resolves selectors on average between 26 and 32 ms on this i5 pixelbook in chrome. So even at 3x the number of selectors it seems like it should be faster.
 
There's likely a far more efficient dependency resolution algorithm than what I put together here. That'd be another thing that could be worth investigating.

Things that would be really interesting to know is how many times it runs that resolve loop. There's a neat little hack where you can insert a "conditional breakpoint" that is actually a console.log

![image](https://user-images.githubusercontent.com/67925/52258679-ddbf7280-28d4-11e9-9aae-75cbd5141a5a.png)

If you open "sources" in chrome, locate the file in question, click the "pretty print"' option and then CMD+F to search for > 500 you should be able to locate the line. If you click "'edit breakpoint" you can insert a log statement, then  refresh the page. 

That will tell us how many times it's running. I'm definitely curious to hear what's causing you to hit this limit.  Obviously you have a pretty high number of selectors, but even so it seems strange that you'd be hitting this limit.

**Comment by layflags** [comment]
Thanks for replying Henrik! 

I can even reproduce this now on Mac OS (Mojave) with Chrome (71) by just throttling the CPU to `4x slowdown` with `duration` values around ~1250 msec (with `6x slowdown` it's ~1830 msec).

My system: MacBook Pro (Retina, 15-inch, Mid 2015), 2,8 GHz Intel Core i7, 16 GB 1600 MHz DDR3 

Don't have a clue why this is happening or how to effectively debug this problem further?!

When defining my selectors/reactors with `createSelector`, is it better/faster to use string refs. or functions? I often use functions inside bundles referencing my local selectors.

I think I'll now try to isolate the bundle causing this issue first. I'll keep you up-to-date!
